# Generated by Django 5.2.4 on 2025-07-26 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(
                blank=True,
                default=datetime.datetime(
                    2025, 7, 26, 18, 31, 16, 235644, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
