# Generated by Django 5.2.4 on 2025-07-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_menuitem_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
