# Generated by Django 5.2.4 on 2025-07-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_menuitem_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="image_url",
        ),
    ]
