# Generated by Django 5.2.4 on 2025-07-27 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_table_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="number_of_people",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
